//
//  HomePresenter.swift
//  Map Weather
//
//  Created by Artashes Noknok on 7/25/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentSuccess(response: Home.Something.Response)
    func presentError(error: String)
    func showLoader()
    func hideLoader()
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentSuccess(response: Home.Something.Response)
    {
        let dispModel:WeatherDispModel = WeatherDispModel(sunset: response.weatherModel.sunset ?? "",
                                                          countryCode: response.weatherModel.countryCode ?? "",
                                                          temp: response.weatherModel.temp ?? 0.0,
                                                          cityName: response.weatherModel.cityName ?? "",
                                                          windSpd: response.weatherModel.windSpd ?? 0.0)
        let viewModel = Home.Something.ViewModel(weattherDispModel:dispModel )
        viewController?.displaySuccess(viewModel: viewModel)
    }
    func presentError(error: String) {
        viewController?.displayError(errorStr: error)
    }
    
    func showLoader() {
        viewController?.showLoader()
    }
    func hideLoader() {
        viewController?.hideLoader()
    }
}
