//
//  HomeWorker.swift
//  Map Weather
//
//  Created by Artashes Noknok on 7/25/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

class HomeWorker
{
    var networkAPI = NetworkAPI(baseUrl: Constants.NetworkingPaths.baseURL!)
    
    func getWeatherInfo(lat:String, lon:String) -> Observable<WeatherModel>
    {
        let weatherQuery = WeatherQuery(method: Constants.APIKeysAndMethods.current, lat: lat, lon: lon, key: Constants.NetworkAPIKey.key)
        return networkAPI.query(data: weatherQuery)
    }
}
